spring.application.name=news-aggregator

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:newsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update # Creates/updates schema on startup

jwt.secret=lgyB6hkeg6RfX2_GMZJa9Wj1h8IVb8Bm-93mz4CzxR4

newsapi.org.api-key=YOUR_NEWSAPI_ORG_KEY
newscatcherapi.com.api-key=YOUR_NEWSCATCHERAPI_COM_KEY
gnews.io.api-key=YOUR_GNEWS_IO_KEY